import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter instead of Geist
import "./globals.css";
import { ThemeProvider } from "@/provider/ThemeProvider";
import { ReduxProvider } from "@/provider/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import "regenerator-runtime/runtime";

const inter = Inter({
  variable: "--font-inter", // Updated variable name to reflect Inter
  subsets: ["latin"],
  // Optional: You can specify weight and style if needed
  weight: ["300", "400", "500", "600", "700"], // Adjust weights as per your design
  display: "swap", // Improves font loading performance
});

export const metadata: Metadata = {
  title: "tatari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased w-full mx-auto min-h-screen overflow-x-hidden`}
      >
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}